### ISSUE TITLE
Add SX support

### ISSUE THREAD

**Issue by manpaint** [clienthax/higurashimeitool#1] opened 2021-01-18 22:28 UTC
SxamTools has been updated to decode Sx1.05 files. I would like to have an update to this tool so that we can obtain the sprites on Windows.

Alaso ignore the pull request, that was a misclick.

Thanks.

**Comment by clienthax** [comment] 2021-01-19 18:23
Will take a look soon.

**Comment by clienthax** [comment] 2021-01-21 11:52
Hm, either the ktx viewer im using isn't great (it ignores rotation metadata atleast)
Or the colour channels are wrong here

![image](https://user-images.githubusercontent.com/1056270/105347668-1d291b80-5bdf-11eb-93ab-629cb1881a86.png)

Aha seems mentioned on the SxamTools info
```
For files with an ImageA (types 2 and 3), Image contains the final image's red and green channels, while ImageA contains its blue and alpha, therefore to create the final image, use the following mapping:

Final.R = Image.R
Final.G = Image.G
Final.B = ImageA.R
Final.A = ImageA.B
```

**Comment by clienthax** [comment] 2021-01-28 10:23
Having issues with finding a suitable library in go that can do software decoding of these images (ETC2)

**Comment by manpaint** [comment] 2021-01-28 15:03
> Having issues with finding a suitable library in go that can do software decoding of these images (ETC2)

The above image seems to imply that you managed to atleast extract the images in a viewable. If the color correction is an issue, then release the update as it  since we can correct the color channels with photoshop. 

If you stumbled across a different type of file format that you can't convert, then extracting the raw SX files is pretty much all that matter. I'm sure there is some format somewhere that could decode it, since its a format used by Android devs.

**Comment by clienthax** [comment] 2021-01-28 18:17
> > Having issues with finding a suitable library in go that can do software decoding of these images (ETC2)
> 
> The above image seems to imply that you managed to atleast extract the images in a viewable. If the color correction is an issue, then release the update as it since we can correct the color channels with photoshop.
> 
> If you stumbled across a different type of file format that you can't convert, then extracting the raw SX files is pretty much all that matter. I'm sure there is some format somewhere that could decode it, since its a format used by Android devs.

The problem is that i can only export raw ktx files, which are 99% used for hardware decoding, can photoshop even open them?

Ideally I want to be able to decompress the data and fixup the colours etc then convert to a format like png

**Comment by manpaint** [comment] 2021-01-29 11:19
> The problem is that i can only export raw ktx files, which are 99% used for hardware decoding, can photoshop even open them?
> 
> Ideally I want to be able to decompress the data and fixup the colours etc then convert to a format like png

Can you provide me a raw ktx file sample? Ideally the same file-picture shown above.

**Comment by clienthax** [comment] 2021-03-05 15:26
Closing this off for now as I don't believe its 'easily' possible with golang in general without external tools being required,
someone more familiar with KTX can open a PR to add support if wanted.

**Closed as completed by clienthax** 2021-03-05 15:26 UTC
